// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// basic_sample_entropy
NumericVector basic_sample_entropy(NumericVector data, IntegerVector m, NumericVector r, IntegerVector s);
RcppExport SEXP _ParallelSampEn_basic_sample_entropy(SEXP dataSEXP, SEXP mSEXP, SEXP rSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(basic_sample_entropy(data, m, r, s));
    return rcpp_result_gen;
END_RCPP
}
// opencl_sample_entropy
NumericVector opencl_sample_entropy(NumericVector data, IntegerVector m, NumericVector r, IntegerVector s);
RcppExport SEXP _ParallelSampEn_opencl_sample_entropy(SEXP dataSEXP, SEXP mSEXP, SEXP rSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(opencl_sample_entropy(data, m, r, s));
    return rcpp_result_gen;
END_RCPP
}
// createContext
bool createContext();
RcppExport SEXP _ParallelSampEn_createContext() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(createContext());
    return rcpp_result_gen;
END_RCPP
}
// cleanup
void cleanup();
RcppExport SEXP _ParallelSampEn_cleanup() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    cleanup();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ParallelSampEn_basic_sample_entropy", (DL_FUNC) &_ParallelSampEn_basic_sample_entropy, 4},
    {"_ParallelSampEn_opencl_sample_entropy", (DL_FUNC) &_ParallelSampEn_opencl_sample_entropy, 4},
    {"_ParallelSampEn_createContext", (DL_FUNC) &_ParallelSampEn_createContext, 0},
    {"_ParallelSampEn_cleanup", (DL_FUNC) &_ParallelSampEn_cleanup, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ParallelSampEn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
