# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basic_sample_entropy <- function(data, m, r, s) {
    .Call(`_ParallelSampEn_basic_sample_entropy`, data, m, r, s)
}

opencl_sample_entropy <- function(data, m, r, s) {
    .Call(`_ParallelSampEn_opencl_sample_entropy`, data, m, r, s)
}

createContext <- function() {
    .Call(`_ParallelSampEn_createContext`)
}

cleanup <- function() {
    invisible(.Call(`_ParallelSampEn_cleanup`))
}

